#!/bin/sh

commit_msg=`cat $1`

msg_re="^(feat|fix|docs|style|refactor|perf|test|workflow|build|ci|chore|release|workflow)(\([a-zA-Z-]+-[0-9]+.+\))?: .{1,200}"

if [[ ! $commit_msg =~ $msg_re ]]
then
    echo "\nIllegal commit message submission format, please use the correct format: \
    \nfeat(CORE-1922): add comments\
    \nfix: handle events on blur (close #28)\
    \nPlease check the GIT commit submission specification for details: \
    \nhttps://github.com/mole-org/git-hook/blob/style.md"

    exit 1
fi